/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jhonatanarrietaagendajava.Vistas;

import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author jhonda
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();

        this.itemMenuListarPersonasPorEvento = new JMenuItem("  Por Evento");
        MenuListarPersonas.add(itemMenuListarPersonasPorEvento);
        this.itemMenuListarPersonasPorGenero = new JMenuItem("  Por Genero");
        MenuListarPersonas.add(itemMenuListarPersonasPorGenero);
        this.itemMenuListarPersonasPorNombre = new JMenuItem("  Por Nombre");
        MenuListarPersonas.add(itemMenuListarPersonasPorNombre);
        this.itemMenuListarPersonasPorApellido = new JMenuItem("  Por Apellido");
        MenuListarPersonas.add(itemMenuListarPersonasPorApellido);
        this.itemMenuListarPersonasPorEdad = new JMenuItem("  Por Edad");
        MenuListarPersonas.add(itemMenuListarPersonasPorEdad);

        this.menuEstadisticasPersonas = new JMenu("Estadisticas");
        menuPersona.add(menuEstadisticasPersonas);

        this.itemMenuEstadisticasPersonasMasInvitadas = new JMenuItem("  Mas Invitadas");
        menuEstadisticasPersonas.add(itemMenuEstadisticasPersonasMasInvitadas);
        this.itemMenuEstadisticasPersonasMasFaltantes = new JMenuItem("  Mas Fatantes");
        menuEstadisticasPersonas.add(itemMenuEstadisticasPersonasMasFaltantes);
        this.itemMenuEstadisticasPersonasMayorAsistencia = new JMenuItem("  Mayor Asistencia");
        menuEstadisticasPersonas.add(itemMenuEstadisticasPersonasMayorAsistencia);
        this.itemMenuEstadisticasPersonasPromedioDeEdadPorGenero = new JMenuItem("  Promedio De Edad Por Genero");
        menuEstadisticasPersonas.add(itemMenuEstadisticasPersonasPromedioDeEdadPorGenero);

        this.itemMenuListarEventosPorPersona = new JMenuItem("  Por Persona");
        MenuListarEvento.add(itemMenuListarEventosPorPersona);
        this.itemMenuListarEventosPorFecha = new JMenuItem("  Por Fecha");
        MenuListarEvento.add(itemMenuListarEventosPorFecha);

        this.menuEstadisticasEventos = new JMenu("Estadisticas");
        menuEvento.add(menuEstadisticasEventos);

        this.itemMenuEstadisticasEventosPromedioPorFecha = new JMenuItem("  Promedio Por Fecha");
        menuEstadisticasEventos.add(itemMenuEstadisticasEventosPromedioPorFecha);
        this.itemMenuEstadisticasEventosPromedioDeAsistentesYFaltantes = new JMenuItem("  Promedio De Asistentes y Faltantes");
        menuEstadisticasEventos.add(itemMenuEstadisticasEventosPromedioDeAsistentesYFaltantes);
        this.itemMenuEstadisticasEventosMayoresAsistenciaYAudiencia = new JMenuItem("  Mayor Asistencia y Audiencia");
        menuEstadisticasEventos.add(itemMenuEstadisticasEventosMayoresAsistenciaYAudiencia);
        this.itemMenuEstadisticasEventosMasLargosYMasCortos = new JMenuItem("  Mas Largos y Mas Cortos");
        menuEstadisticasEventos.add(itemMenuEstadisticasEventosMasLargosYMasCortos);
        
        this.itemMenuListarInvitacionesPorPersona = new JMenuItem(" Por Persona");
        MenuListarInvitacion.add(itemMenuListarEventosPorPersona);
        this.itemMenuListarInvitacionesPorEvento = new JMenuItem("  Por Evento");
        MenuListarInvitacion.add(itemMenuListarInvitacionesPorEvento);
        
        this.menuEstadisticasInvitaciones = new JMenuItem("Estadisticas");
        MenuConsultarInvitacion.add(menuEstadisticasInvitaciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        menuSesion = new javax.swing.JMenu();
        itemMenuSesionInicio = new javax.swing.JMenuItem();
        itemMenuSesionSalir = new javax.swing.JMenuItem();
        menuPersona = new javax.swing.JMenu();
        itemMenuAgregarPersona = new javax.swing.JMenuItem();
        itemMenuConsultarPersona = new javax.swing.JMenuItem();
        itemMenuEliminarPersona = new javax.swing.JMenuItem();
        itemMenuModificarPersona = new javax.swing.JMenuItem();
        MenuListarPersonas = new javax.swing.JMenu();
        menuEvento = new javax.swing.JMenu();
        itemMenuAgregarEvento = new javax.swing.JMenuItem();
        itemMenuConsultarEvento = new javax.swing.JMenuItem();
        itemMenuEliminarEvento = new javax.swing.JMenuItem();
        itemMenuModificarEvento = new javax.swing.JMenuItem();
        MenuListarEvento = new javax.swing.JMenu();
        MenuConsultarInvitacion = new javax.swing.JMenu();
        itemMenuAgregarInvitacion = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        itemMenuEliminarInvitacion = new javax.swing.JMenuItem();
        itemMenuModificarInvitacion = new javax.swing.JMenuItem();
        MenuListarInvitacion = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenu();
        itemMenuAyudaAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuSesion.setText("Sesion");

        itemMenuSesionInicio.setText("Iniciar");
        menuSesion.add(itemMenuSesionInicio);

        itemMenuSesionSalir.setText("Salir");
        menuSesion.add(itemMenuSesionSalir);

        barraMenu.add(menuSesion);

        menuPersona.setText("Persona");

        itemMenuAgregarPersona.setText("Agregar");
        itemMenuAgregarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAgregarPersonaActionPerformed(evt);
            }
        });
        menuPersona.add(itemMenuAgregarPersona);

        itemMenuConsultarPersona.setText("Consultar");
        itemMenuConsultarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuConsultarPersonaActionPerformed(evt);
            }
        });
        menuPersona.add(itemMenuConsultarPersona);

        itemMenuEliminarPersona.setText("Eliminar");
        itemMenuEliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuEliminarPersonaActionPerformed(evt);
            }
        });
        menuPersona.add(itemMenuEliminarPersona);

        itemMenuModificarPersona.setText("Modificar");
        itemMenuModificarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuModificarPersonaActionPerformed(evt);
            }
        });
        menuPersona.add(itemMenuModificarPersona);

        MenuListarPersonas.setText("Listar");
        menuPersona.add(MenuListarPersonas);

        barraMenu.add(menuPersona);

        menuEvento.setText("Evento");

        itemMenuAgregarEvento.setText("Agregar");
        menuEvento.add(itemMenuAgregarEvento);

        itemMenuConsultarEvento.setText("Consultar");
        menuEvento.add(itemMenuConsultarEvento);

        itemMenuEliminarEvento.setText("Eliminar");
        menuEvento.add(itemMenuEliminarEvento);

        itemMenuModificarEvento.setText("Modificar");
        menuEvento.add(itemMenuModificarEvento);

        MenuListarEvento.setText("Listar");
        menuEvento.add(MenuListarEvento);

        barraMenu.add(menuEvento);

        MenuConsultarInvitacion.setText("Invitacion");

        itemMenuAgregarInvitacion.setText("Agregar");
        MenuConsultarInvitacion.add(itemMenuAgregarInvitacion);

        jMenuItem1.setText("Consultar");
        MenuConsultarInvitacion.add(jMenuItem1);

        itemMenuEliminarInvitacion.setText("Eliminar");
        MenuConsultarInvitacion.add(itemMenuEliminarInvitacion);

        itemMenuModificarInvitacion.setText("Modificar");
        MenuConsultarInvitacion.add(itemMenuModificarInvitacion);

        MenuListarInvitacion.setText("Listar");
        MenuConsultarInvitacion.add(MenuListarInvitacion);

        barraMenu.add(MenuConsultarInvitacion);

        menuAyuda.setText("Ayuda");

        itemMenuAyudaAcercaDe.setText("Acerca de");
        menuAyuda.add(itemMenuAyudaAcercaDe);

        barraMenu.add(menuAyuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuAgregarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAgregarPersonaActionPerformed
        // TODO add your handling code here:
        VentanaAgregarPersonas VentanaAP = new VentanaAgregarPersonas(this, true);
        VentanaAP.setLocationRelativeTo(null);
        VentanaAP.setVisible(true);
    }//GEN-LAST:event_itemMenuAgregarPersonaActionPerformed

    private void itemMenuConsultarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuConsultarPersonaActionPerformed
        // TODO add your handling code here:
        VentanaBuscarPersonas VentanaCP = new VentanaBuscarPersonas(this, true);
        VentanaCP.setLocationRelativeTo(null);
        VentanaCP.setVisible(true);

    }//GEN-LAST:event_itemMenuConsultarPersonaActionPerformed

    private void itemMenuEliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuEliminarPersonaActionPerformed
        // TODO add your handling code here:
        VentanaEliminarPersonas VentanaEP = new VentanaEliminarPersonas(this, true);
        VentanaEP.setLocationRelativeTo(null);
        VentanaEP.setVisible(true);
    }//GEN-LAST:event_itemMenuEliminarPersonaActionPerformed

    private void itemMenuModificarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuModificarPersonaActionPerformed
        // TODO add your handling code here:
        VentanaListarPersonas VentanaLP = new VentanaListarPersonas(this, true);
        VentanaLP.setLocationRelativeTo(null);
        VentanaLP.setVisible(true);
    }//GEN-LAST:event_itemMenuModificarPersonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
    }
    private javax.swing.JMenuItem itemMenuListarPersonasPorEvento;
    private javax.swing.JMenuItem itemMenuListarPersonasPorGenero;
    private javax.swing.JMenuItem itemMenuListarPersonasPorNombre;
    private javax.swing.JMenuItem itemMenuListarPersonasPorApellido;
    private javax.swing.JMenuItem itemMenuListarPersonasPorEdad;
    private javax.swing.JMenu menuEstadisticasPersonas;
    private javax.swing.JMenuItem itemMenuEstadisticasPersonasMasInvitadas;
    private javax.swing.JMenuItem itemMenuEstadisticasPersonasMasFaltantes;
    private javax.swing.JMenuItem itemMenuEstadisticasPersonasMayorAsistencia;
    private javax.swing.JMenuItem itemMenuEstadisticasPersonasPromedioDeEdadPorGenero;

    private javax.swing.JMenuItem itemMenuListarEventosPorPersona;
    private javax.swing.JMenuItem itemMenuListarEventosPorFecha;
    private javax.swing.JMenu menuEstadisticasEventos;
    private javax.swing.JMenuItem itemMenuEstadisticasEventosPromedioPorFecha;
    private javax.swing.JMenuItem itemMenuEstadisticasEventosPromedioDeAsistentesYFaltantes;
    private javax.swing.JMenuItem itemMenuEstadisticasEventosMayoresAsistenciaYAudiencia;
    private javax.swing.JMenuItem itemMenuEstadisticasEventosMasLargosYMasCortos;

    private javax.swing.JMenuItem itemMenuListarInvitacionesPorPersona;
    private javax.swing.JMenuItem itemMenuListarInvitacionesPorEvento;
    
    private javax.swing.JMenuItem menuEstadisticasInvitaciones;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuConsultarInvitacion;
    private javax.swing.JMenu MenuListarEvento;
    private javax.swing.JMenu MenuListarInvitacion;
    private javax.swing.JMenu MenuListarPersonas;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itemMenuAgregarEvento;
    private javax.swing.JMenuItem itemMenuAgregarInvitacion;
    private javax.swing.JMenuItem itemMenuAgregarPersona;
    private javax.swing.JMenuItem itemMenuAyudaAcercaDe;
    private javax.swing.JMenuItem itemMenuConsultarEvento;
    private javax.swing.JMenuItem itemMenuConsultarPersona;
    private javax.swing.JMenuItem itemMenuEliminarEvento;
    private javax.swing.JMenuItem itemMenuEliminarInvitacion;
    private javax.swing.JMenuItem itemMenuEliminarPersona;
    private javax.swing.JMenuItem itemMenuModificarEvento;
    private javax.swing.JMenuItem itemMenuModificarInvitacion;
    private javax.swing.JMenuItem itemMenuModificarPersona;
    private javax.swing.JMenuItem itemMenuSesionInicio;
    private javax.swing.JMenuItem itemMenuSesionSalir;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuEvento;
    private javax.swing.JMenu menuPersona;
    private javax.swing.JMenu menuSesion;
    // End of variables declaration//GEN-END:variables
}
